This is makeindex, version 2.15 [TeX Live 2019] (kpathsea + Thai support).
Scanning style file ./examplethesis.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file examplethesis.acn....done (25 entries accepted, 0 rejected).
Sorting entries....done (111 comparisons).
Generating output file examplethesis.acr....done (63 lines written, 0 warnings).
Output written in examplethesis.acr.
Transcript written in examplethesis.alg.
